// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alktmdmqgouypyznmjia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsa3RtZG1xZ291eXB5em5tamlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDczNDMsImV4cCI6MjA3MTU4MzM0M30.EXIeWnBAHIHhThuKonwewb9fDVWHlYaLTzxYKMCaYqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});